[project]
name = "pdbgen2"
version = "0.1.0"

[target.myexecutable]
type = "executable"
sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include"]
compile-features = ["cxx_std_17"]

cmake-before = """
include(FetchContent)
Set(FETCHCONTENT_QUIET FALSE)

FetchContent_Declare(
    llvm
    GIT_REPOSITORY https://github.com/llvm/llvm-project.git
    GIT_TAG llvmorg-18.1.6
    GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(llvm)
find_package(LLVM REQUIRED CONFIG)

message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")

include_directories(${LLVM_INCLUDE_DIRS})
add_definitions(${LLVM_DEFINITIONS})
llvm_map_components_to_libnames(llvm_libs debuginfopdb)
"""

cmake-after = """
target_link_libraries(pdbgen2 ${llvm_libs})
"""